-- 250 palabras adicionales con categoria, pista y dificultad.
-- Puede ejecutarse varias veces: las palabras existentes se actualizan sin duplicarse.
USE Score;

INSERT INTO palabras (palabra, categoria, pista, dificultad) VALUES
('leon', 'animales', 'Felino conocido como el rey de la selva.', 'facil'),
('tigre', 'animales', 'Felino grande con rayas negras.', 'facil'),
('pantera', 'animales', 'Felino de pelaje generalmente oscuro.', 'media'),
('cebra', 'animales', 'Animal africano con rayas blancas y negras.', 'facil'),
('rinoceronte', 'animales', 'Mamifero grande con uno o dos cuernos.', 'dificil'),
('hipopotamo', 'animales', 'Mamifero enorme que pasa mucho tiempo en el agua.', 'dificil'),
('canguro', 'animales', 'Marsupial australiano que se desplaza saltando.', 'media'),
('koala', 'animales', 'Marsupial que come hojas de eucalipto.', 'facil'),
('pinguino', 'animales', 'Ave marina que no vuela y vive en zonas frias.', 'media'),
('aguila', 'animales', 'Ave rapaz de gran vista y vuelo poderoso.', 'facil'),
('halcon', 'animales', 'Ave rapaz famosa por su velocidad.', 'media'),
('buho', 'animales', 'Ave nocturna de grandes ojos.', 'facil'),
('delfin', 'animales', 'Mamifero marino inteligente y sociable.', 'facil'),
('tiburon', 'animales', 'Pez depredador con varias filas de dientes.', 'media'),
('ballena', 'animales', 'El mamifero mas grande del planeta.', 'media'),
('pulpo', 'animales', 'Animal marino con ocho tentaculos.', 'facil'),
('medusa', 'animales', 'Animal marino gelatinoso con tentaculos.', 'media'),
('cangrejo', 'animales', 'Crustaceo que camina de costado.', 'media'),
('caracol', 'animales', 'Molusco lento que lleva su casa encima.', 'facil'),
('mariposa', 'animales', 'Insecto de alas coloridas que nace como oruga.', 'media'),
('hormiga', 'animales', 'Insecto pequeño que vive en colonias.', 'facil'),
('abeja', 'animales', 'Insecto que produce miel.', 'facil'),
('arana', 'animales', 'Aracnido de ocho patas que teje redes.', 'facil'),
('serpiente', 'animales', 'Reptil alargado que no tiene patas.', 'media'),
('tortuga', 'animales', 'Reptil protegido por un caparazon.', 'facil'),

('banana', 'comida', 'Fruta amarilla y alargada.', 'facil'),
('naranja', 'comida', 'Fruta citrica del mismo nombre que su color.', 'facil'),
('pera', 'comida', 'Fruta verde o amarilla con base redondeada.', 'facil'),
('frutilla', 'comida', 'Fruta roja pequeña con semillas exteriores.', 'media'),
('sandia', 'comida', 'Fruta grande, verde por fuera y roja por dentro.', 'facil'),
('melon', 'comida', 'Fruta redonda de pulpa dulce y muchas semillas.', 'facil'),
('uva', 'comida', 'Fruta pequeña que crece en racimos.', 'facil'),
('durazno', 'comida', 'Fruta de piel aterciopelada y carozo central.', 'media'),
('limon', 'comida', 'Fruta amarilla de sabor muy acido.', 'facil'),
('zanahoria', 'comida', 'Verdura naranja que crece bajo tierra.', 'media'),
('papa', 'comida', 'Tuberculo usado para hacer pure y papas fritas.', 'facil'),
('tomate', 'comida', 'Fruto rojo muy usado en ensaladas y salsas.', 'facil'),
('lechuga', 'comida', 'Verdura de hojas verdes usada en ensaladas.', 'media'),
('cebolla', 'comida', 'Vegetal en capas que puede hacerte llorar.', 'media'),
('queso', 'comida', 'Alimento elaborado principalmente con leche.', 'facil'),
('pan', 'comida', 'Alimento horneado hecho con harina y agua.', 'facil'),
('arroz', 'comida', 'Cereal blanco que acompaña muchos platos.', 'facil'),
('sopa', 'comida', 'Preparacion liquida que suele servirse caliente.', 'facil'),
('pizza', 'comida', 'Masa redonda con salsa, queso y otros ingredientes.', 'facil'),
('hamburguesa', 'comida', 'Medallon servido generalmente entre dos panes.', 'dificil'),
('empanada', 'comida', 'Masa rellena y cerrada que se hornea o se frie.', 'media'),
('milanesa', 'comida', 'Filete empanado muy popular en Argentina.', 'media'),
('helado', 'comida', 'Postre frio y cremoso de muchos sabores.', 'facil'),
('chocolate', 'comida', 'Dulce elaborado a partir del cacao.', 'media'),
('galleta', 'comida', 'Pequeño alimento horneado, dulce o salado.', 'facil'),

('tenis', 'deportes', 'Deporte de raqueta jugado sobre una red.', 'facil'),
('voley', 'deportes', 'Dos equipos pasan una pelota por encima de una red.', 'facil'),
('handball', 'deportes', 'Deporte de equipo donde la pelota se juega con las manos.', 'media'),
('rugby', 'deportes', 'Deporte de contacto con una pelota ovalada.', 'media'),
('hockey', 'deportes', 'Se juega impulsando una pelota o disco con un palo.', 'media'),
('golf', 'deportes', 'Consiste en introducir una pelota en hoyos con pocos golpes.', 'facil'),
('natacion', 'deportes', 'Deporte que se practica desplazandose en el agua.', 'media'),
('atletismo', 'deportes', 'Incluye carreras, saltos y lanzamientos.', 'media'),
('ciclismo', 'deportes', 'Deporte realizado sobre una bicicleta.', 'media'),
('boxeo', 'deportes', 'Dos rivales combaten con guantes dentro de un ring.', 'facil'),
('judo', 'deportes', 'Arte marcial japones basado en agarres y proyecciones.', 'facil'),
('karate', 'deportes', 'Arte marcial de golpes originado en Japon.', 'facil'),
('surf', 'deportes', 'Deporte de deslizarse sobre las olas.', 'facil'),
('remo', 'deportes', 'Deporte acuatico que impulsa una embarcacion con palas.', 'facil'),
('ajedrez', 'deportes', 'Juego de estrategia con rey, reina y peones.', 'media'),
('patinaje', 'deportes', 'Actividad de desplazarse sobre patines.', 'media'),
('beisbol', 'deportes', 'Deporte de bate, pelota y cuatro bases.', 'media'),
('softbol', 'deportes', 'Deporte parecido al beisbol con pelota mas grande.', 'media'),
('esqui', 'deportes', 'Deporte de nieve practicado con dos tablas largas.', 'facil'),
('snowboard', 'deportes', 'Descenso sobre nieve con una sola tabla.', 'dificil'),
('triatlon', 'deportes', 'Combina natacion, ciclismo y carrera.', 'media'),
('maraton', 'deportes', 'Carrera de larga distancia de poco mas de 42 kilometros.', 'media'),
('gimnasia', 'deportes', 'Disciplina de fuerza, equilibrio y flexibilidad.', 'media'),
('waterpolo', 'deportes', 'Deporte de pelota por equipos dentro de una piscina.', 'dificil'),
('automovilismo', 'deportes', 'Competicion de velocidad realizada con autos.', 'dificil'),

('continente', 'geografia', 'Gran extension de tierra separada por oceanos.', 'media'),
('oceano', 'geografia', 'Enorme masa de agua salada.', 'facil'),
('rio', 'geografia', 'Corriente natural de agua que desemboca en otra masa.', 'facil'),
('lago', 'geografia', 'Masa de agua rodeada de tierra.', 'facil'),
('valle', 'geografia', 'Terreno bajo situado entre montañas.', 'facil'),
('desierto', 'geografia', 'Region muy seca con pocas precipitaciones.', 'media'),
('glaciar', 'geografia', 'Gran masa de hielo que se desplaza lentamente.', 'media'),
('bosque', 'geografia', 'Terreno cubierto principalmente por arboles.', 'facil'),
('selva', 'geografia', 'Bosque tropical denso y lluvioso.', 'facil'),
('pradera', 'geografia', 'Terreno extenso cubierto de pastos.', 'media'),
('meseta', 'geografia', 'Llanura extensa situada a cierta altura.', 'media'),
('cordillera', 'geografia', 'Conjunto extenso de montañas enlazadas.', 'dificil'),
('isla', 'geografia', 'Porcion de tierra rodeada de agua.', 'facil'),
('peninsula', 'geografia', 'Tierra rodeada de agua salvo por una parte.', 'dificil'),
('bahia', 'geografia', 'Entrada del mar en la costa, menor que un golfo.', 'media'),
('golfo', 'geografia', 'Gran entrada del mar en la tierra.', 'facil'),
('cabo', 'geografia', 'Punta de tierra que se adentra en el mar.', 'facil'),
('canion', 'geografia', 'Paso estrecho y profundo entre paredes rocosas.', 'media'),
('cascada', 'geografia', 'Caida natural de agua desde cierta altura.', 'media'),
('laguna', 'geografia', 'Deposito natural de agua menor que un lago.', 'facil'),
('estuario', 'geografia', 'Zona donde un rio se mezcla con el mar.', 'dificil'),
('delta', 'geografia', 'Terreno triangular formado en la desembocadura de un rio.', 'media'),
('fiordo', 'geografia', 'Entrada estrecha del mar entre montañas escarpadas.', 'dificil'),
('acantilado', 'geografia', 'Pendiente rocosa casi vertical junto al mar.', 'dificil'),
('sabana', 'geografia', 'Llanura tropical con pastos y pocos arboles.', 'media'),

('monitor', 'tecnologia', 'Pantalla donde se muestra la informacion de una computadora.', 'facil'),
('raton', 'tecnologia', 'Dispositivo que mueve el puntero en la pantalla.', 'facil'),
('impresora', 'tecnologia', 'Dispositivo que lleva documentos digitales al papel.', 'media'),
('router', 'tecnologia', 'Equipo que distribuye la conexion de una red.', 'media'),
('servidor', 'tecnologia', 'Computadora que ofrece recursos a otros equipos.', 'media'),
('basedatos', 'tecnologia', 'Conjunto organizado de informacion consultable.', 'dificil'),
('programacion', 'tecnologia', 'Proceso de crear instrucciones para una computadora.', 'dificil'),
('codigo', 'tecnologia', 'Conjunto de instrucciones escritas por un programador.', 'facil'),
('variable', 'tecnologia', 'Espacio con nombre que almacena un valor.', 'media'),
('funcion', 'tecnologia', 'Bloque reutilizable de instrucciones.', 'media'),
('compilador', 'tecnologia', 'Programa que traduce codigo a otro lenguaje ejecutable.', 'dificil'),
('navegador', 'tecnologia', 'Programa usado para visitar paginas web.', 'media'),
('internet', 'tecnologia', 'Red mundial que conecta dispositivos.', 'facil'),
('redes', 'tecnologia', 'Sistemas que permiten comunicar varios dispositivos.', 'facil'),
('software', 'tecnologia', 'Conjunto de programas de un dispositivo.', 'media'),
('hardware', 'tecnologia', 'Componentes fisicos de una computadora.', 'media'),
('memoria', 'tecnologia', 'Componente que almacena datos temporal o permanentemente.', 'media'),
('procesador', 'tecnologia', 'Componente que ejecuta instrucciones y calculos.', 'dificil'),
('robot', 'tecnologia', 'Maquina programable capaz de realizar tareas.', 'facil'),
('sensor', 'tecnologia', 'Dispositivo que detecta cambios del entorno.', 'media'),
('aplicacion', 'tecnologia', 'Programa diseñado para cumplir una tarea especifica.', 'media'),
('contrasenia', 'tecnologia', 'Clave secreta usada para proteger una cuenta.', 'dificil'),
('ciberseguridad', 'tecnologia', 'Proteccion de sistemas y datos frente a ataques.', 'dificil'),
('interfaz', 'tecnologia', 'Medio visual para interactuar con un sistema.', 'media'),
('terminal', 'tecnologia', 'Herramienta de texto para ejecutar comandos.', 'media'),

('piano', 'musica', 'Instrumento de teclas blancas y negras.', 'facil'),
('violin', 'musica', 'Instrumento de cuerda que se toca con arco.', 'facil'),
('viola', 'musica', 'Instrumento de cuerda similar al violin, algo mayor.', 'media'),
('violonchelo', 'musica', 'Instrumento de cuerda grande que se apoya en el suelo.', 'dificil'),
('flauta', 'musica', 'Instrumento de viento alargado con orificios.', 'facil'),
('clarinete', 'musica', 'Instrumento de viento de madera con una sola lengueta.', 'media'),
('trompeta', 'musica', 'Instrumento de metal de sonido brillante.', 'media'),
('trombon', 'musica', 'Instrumento de metal con una vara deslizante.', 'media'),
('arpa', 'musica', 'Instrumento triangular con muchas cuerdas.', 'facil'),
('acordeon', 'musica', 'Instrumento con fuelle, teclas y botones.', 'media'),
('bateria', 'musica', 'Conjunto de tambores y platillos.', 'facil'),
('xilofon', 'musica', 'Instrumento de laminas que se golpean con baquetas.', 'media'),
('armonica', 'musica', 'Pequeño instrumento que se toca soplando y aspirando.', 'media'),
('mandolina', 'musica', 'Instrumento pequeño de cuerdas pulsadas.', 'dificil'),
('ukelele', 'musica', 'Instrumento hawaiano parecido a una guitarra pequeña.', 'media'),
('orquesta', 'musica', 'Gran conjunto de musicos e instrumentos.', 'media'),
('melodia', 'musica', 'Sucesion de notas que forma una idea musical.', 'media'),
('ritmo', 'musica', 'Patron temporal que organiza los sonidos.', 'facil'),
('acorde', 'musica', 'Conjunto de notas que suenan al mismo tiempo.', 'media'),
('partitura', 'musica', 'Documento donde se escribe una composicion musical.', 'media'),
('microfono', 'musica', 'Dispositivo que capta y amplifica sonidos.', 'media'),
('concierto', 'musica', 'Presentacion musical frente a un publico.', 'media'),
('cantante', 'musica', 'Persona que usa su voz para interpretar musica.', 'facil'),
('compositor', 'musica', 'Persona que crea obras musicales.', 'dificil'),
('director', 'musica', 'Persona que guia a los integrantes de una orquesta.', 'media'),

('atomo', 'ciencia', 'Unidad basica de la materia.', 'facil'),
('molecula', 'ciencia', 'Conjunto de atomos unidos entre si.', 'media'),
('celula', 'ciencia', 'Unidad estructural basica de los seres vivos.', 'facil'),
('tejido', 'ciencia', 'Conjunto organizado de celulas similares.', 'media'),
('organo', 'ciencia', 'Parte del cuerpo formada por varios tejidos.', 'facil'),
('energia', 'ciencia', 'Capacidad para producir trabajo o cambios.', 'media'),
('fuerza', 'ciencia', 'Interaccion capaz de cambiar el movimiento de un cuerpo.', 'facil'),
('gravedad', 'ciencia', 'Fuerza que atrae los cuerpos hacia la Tierra.', 'media'),
('planeta', 'ciencia', 'Cuerpo celeste que orbita una estrella.', 'facil'),
('estrella', 'ciencia', 'Esfera luminosa de gas que produce energia.', 'media'),
('galaxia', 'ciencia', 'Enorme conjunto de estrellas, gas y polvo.', 'media'),
('cometa', 'ciencia', 'Cuerpo helado que puede formar una cola al acercarse al Sol.', 'facil'),
('asteroide', 'ciencia', 'Cuerpo rocoso menor que un planeta.', 'media'),
('nebulosa', 'ciencia', 'Nube interestelar de gas y polvo.', 'media'),
('telescopio', 'ciencia', 'Instrumento para observar objetos muy lejanos.', 'dificil'),
('microscopio', 'ciencia', 'Instrumento para observar objetos diminutos.', 'dificil'),
('quimica', 'ciencia', 'Ciencia que estudia la composicion de la materia.', 'media'),
('fisica', 'ciencia', 'Ciencia que estudia materia, energia y movimiento.', 'facil'),
('biologia', 'ciencia', 'Ciencia que estudia a los seres vivos.', 'media'),
('genetica', 'ciencia', 'Rama que estudia la herencia biologica.', 'media'),
('evolucion', 'ciencia', 'Cambio de las especies a lo largo del tiempo.', 'media'),
('ecosistema', 'ciencia', 'Seres vivos y ambiente que interactuan en un lugar.', 'dificil'),
('fosil', 'ciencia', 'Resto o huella de un organismo antiguo.', 'facil'),
('bacteria', 'ciencia', 'Organismo microscopico de una sola celula.', 'media'),
('virus', 'ciencia', 'Agente infeccioso que necesita una celula para reproducirse.', 'facil'),

('arbol', 'naturaleza', 'Planta de tronco leñoso y gran altura.', 'facil'),
('flor', 'naturaleza', 'Parte colorida de muchas plantas.', 'facil'),
('semilla', 'naturaleza', 'Estructura de la que puede nacer una nueva planta.', 'facil'),
('raiz', 'naturaleza', 'Parte de la planta que absorbe agua del suelo.', 'facil'),
('tronco', 'naturaleza', 'Tallo principal y leñoso de un arbol.', 'facil'),
('rama', 'naturaleza', 'Parte que nace del tronco y sostiene hojas.', 'facil'),
('hoja', 'naturaleza', 'Parte verde de la planta que capta luz.', 'facil'),
('pasto', 'naturaleza', 'Plantas bajas que cubren el suelo.', 'facil'),
('musgo', 'naturaleza', 'Planta pequeña que crece en lugares humedos.', 'media'),
('hongo', 'naturaleza', 'Organismo que no es planta ni animal.', 'facil'),
('roca', 'naturaleza', 'Material solido natural formado por minerales.', 'facil'),
('arena', 'naturaleza', 'Conjunto de pequeños granos de roca.', 'facil'),
('tierra', 'naturaleza', 'Suelo donde crecen muchas plantas.', 'facil'),
('lluvia', 'naturaleza', 'Agua que cae de las nubes en gotas.', 'facil'),
('nieve', 'naturaleza', 'Cristales de hielo que caen de las nubes.', 'facil'),
('granizo', 'naturaleza', 'Precipitacion en forma de bolas de hielo.', 'media'),
('trueno', 'naturaleza', 'Sonido producido durante una tormenta electrica.', 'media'),
('relampago', 'naturaleza', 'Destello luminoso de una descarga electrica.', 'media'),
('viento', 'naturaleza', 'Movimiento del aire en la atmosfera.', 'facil'),
('nube', 'naturaleza', 'Masa visible de gotas suspendidas en el cielo.', 'facil'),
('arcoiris', 'naturaleza', 'Arco de colores que aparece con sol y lluvia.', 'media'),
('aurora', 'naturaleza', 'Luz que aparece en el cielo antes del amanecer.', 'media'),
('amanecer', 'naturaleza', 'Momento en que comienza a salir el Sol.', 'media'),
('atardecer', 'naturaleza', 'Momento en que el Sol se aproxima al horizonte.', 'media'),
('tormenta', 'naturaleza', 'Fenomeno con lluvia, viento y a veces rayos.', 'media'),

('medico', 'profesiones', 'Profesional que diagnostica y trata enfermedades.', 'facil'),
('enfermero', 'profesiones', 'Profesional que cuida y asiste a pacientes.', 'media'),
('docente', 'profesiones', 'Persona que enseña a estudiantes.', 'facil'),
('abogado', 'profesiones', 'Profesional que asesora y representa legalmente.', 'media'),
('arquitecto', 'profesiones', 'Profesional que diseña edificios y espacios.', 'dificil'),
('ingeniero', 'profesiones', 'Profesional que aplica ciencia para resolver problemas.', 'media'),
('carpintero', 'profesiones', 'Persona que fabrica y repara objetos de madera.', 'media'),
('electricista', 'profesiones', 'Especialista en instalaciones electricas.', 'dificil'),
('plomero', 'profesiones', 'Especialista en cañerias y sistemas de agua.', 'media'),
('mecanico', 'profesiones', 'Persona que repara maquinas y vehiculos.', 'media'),
('cocinero', 'profesiones', 'Persona que prepara alimentos profesionalmente.', 'facil'),
('panadero', 'profesiones', 'Persona que elabora pan y productos horneados.', 'media'),
('bombero', 'profesiones', 'Profesional que combate incendios y realiza rescates.', 'facil'),
('policia', 'profesiones', 'Persona encargada de proteger el orden publico.', 'facil'),
('piloto', 'profesiones', 'Persona que conduce una aeronave.', 'facil'),
('periodista', 'profesiones', 'Profesional que investiga y comunica noticias.', 'dificil'),
('fotografo', 'profesiones', 'Persona que crea imagenes con una camara.', 'media'),
('disenador', 'profesiones', 'Profesional que crea soluciones visuales o funcionales.', 'media'),
('programador', 'profesiones', 'Persona que escribe codigo para crear software.', 'dificil'),
('cientifico', 'profesiones', 'Persona que investiga mediante el metodo cientifico.', 'dificil'),
('astronauta', 'profesiones', 'Persona entrenada para viajar al espacio.', 'media'),
('veterinario', 'profesiones', 'Profesional de la salud de los animales.', 'dificil'),
('dentista', 'profesiones', 'Profesional que cuida dientes y boca.', 'media'),
('psicologo', 'profesiones', 'Profesional que estudia conducta y procesos mentales.', 'dificil'),
('contador', 'profesiones', 'Profesional que registra y analiza finanzas.', 'media'),

('mesa', 'objetos', 'Mueble con superficie plana y patas.', 'facil'),
('silla', 'objetos', 'Mueble usado para sentarse.', 'facil'),
('puerta', 'objetos', 'Elemento que permite entrar o salir de un lugar.', 'facil'),
('ventana', 'objetos', 'Abertura que deja pasar luz y aire.', 'facil'),
('lampara', 'objetos', 'Objeto que produce o sostiene una fuente de luz.', 'media'),
('reloj', 'objetos', 'Objeto utilizado para medir y mostrar la hora.', 'facil'),
('espejo', 'objetos', 'Superficie que refleja imagenes.', 'facil'),
('botella', 'objetos', 'Recipiente de cuello estrecho para liquidos.', 'facil'),
('vaso', 'objetos', 'Recipiente pequeño usado para beber.', 'facil'),
('taza', 'objetos', 'Recipiente con asa usado para bebidas.', 'facil'),
('plato', 'objetos', 'Recipiente plano donde se sirve comida.', 'facil'),
('cuchara', 'objetos', 'Cubierto con una parte concava.', 'facil'),
('tenedor', 'objetos', 'Cubierto con varias puntas.', 'facil'),
('cuchillo', 'objetos', 'Utensilio con hoja afilada para cortar.', 'media'),
('mochila', 'objetos', 'Bolso que se lleva en la espalda.', 'facil'),
('cuaderno', 'objetos', 'Conjunto de hojas unidas para escribir.', 'media'),
('lapiz', 'objetos', 'Instrumento de escritura con grafito.', 'facil'),
('borrador', 'objetos', 'Objeto usado para eliminar trazos de lapiz.', 'media'),
('tijera', 'objetos', 'Herramienta de dos hojas para cortar.', 'facil'),
('martillo', 'objetos', 'Herramienta usada para clavar o golpear.', 'media'),
('destornillador', 'objetos', 'Herramienta usada para ajustar tornillos.', 'dificil'),
('llave', 'objetos', 'Objeto que abre una cerradura.', 'facil'),
('paraguas', 'objetos', 'Objeto que protege de la lluvia.', 'media'),
('bicicleta', 'objetos', 'Vehiculo de dos ruedas impulsado con pedales.', 'media'),
('telefono', 'objetos', 'Dispositivo utilizado para comunicarse a distancia.', 'media')
ON DUPLICATE KEY UPDATE
  categoria = VALUES(categoria),
  pista = VALUES(pista),
  dificultad = VALUES(dificultad);
