CREATE TABLE IF NOT EXISTS administradores (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS perfil (
  id TINYINT UNSIGNED PRIMARY KEY DEFAULT 1,
  nombre VARCHAR(80) NOT NULL,
  rol VARCHAR(120) NOT NULL,
  saludo VARCHAR(120) NOT NULL,
  presentacion VARCHAR(500) NOT NULL,
  descripcion TEXT NOT NULL,
  ubicacion VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL,
  disponibilidad VARCHAR(120) NOT NULL,
  retrato_url VARCHAR(500) NOT NULL,
  cv_url VARCHAR(500) NULL,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT perfil_unico CHECK (id = 1)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS enlaces_sociales (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  url VARCHAR(500) NOT NULL,
  orden SMALLINT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS categorias_habilidades (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL UNIQUE,
  imagen_url VARCHAR(500) NOT NULL,
  orden SMALLINT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS habilidades (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL UNIQUE,
  categoria_id INT UNSIGNED NOT NULL,
  nivel TINYINT UNSIGNED NOT NULL DEFAULT 80,
  orden SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  CONSTRAINT nivel_valido CHECK (nivel BETWEEN 1 AND 100),
  CONSTRAINT fk_habilidad_categoria FOREIGN KEY (categoria_id) REFERENCES categorias_habilidades(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS experiencias (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(120) NOT NULL,
  organizacion VARCHAR(120) NOT NULL,
  periodo VARCHAR(80) NOT NULL,
  descripcion VARCHAR(800) NOT NULL,
  orden SMALLINT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS logros (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(120) NOT NULL,
  descripcion VARCHAR(500) NOT NULL,
  fecha VARCHAR(40) NOT NULL,
  orden SMALLINT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS proyectos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(120) NOT NULL,
  resumen VARCHAR(240) NOT NULL,
  descripcion VARCHAR(1200) NOT NULL,
  imagen_url VARCHAR(500) NOT NULL,
  demo_url VARCHAR(500) NULL,
  repo_url VARCHAR(500) NULL,
  destacado BOOLEAN NOT NULL DEFAULT TRUE,
  orden SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tecnologias (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS proyecto_tecnologias (
  proyecto_id INT UNSIGNED NOT NULL,
  tecnologia_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (proyecto_id, tecnologia_id),
  CONSTRAINT fk_pt_proyecto FOREIGN KEY (proyecto_id) REFERENCES proyectos(id) ON DELETE CASCADE,
  CONSTRAINT fk_pt_tecnologia FOREIGN KEY (tecnologia_id) REFERENCES tecnologias(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS mensajes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  email VARCHAR(160) NOT NULL,
  asunto VARCHAR(120) NOT NULL,
  mensaje TEXT NOT NULL,
  leido BOOLEAN NOT NULL DEFAULT FALSE,
  recibido_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_mensajes_recibido (recibido_en),
  INDEX idx_mensajes_leido (leido)
) ENGINE=InnoDB;
